module.exports = gameDummyDatabase = {
  table: [
    [
      {color: 'blue'}, 
      {color: 'red'}, 
      {color: 'purple'}, 
      {color: 'green'}, 
      {color: 'purple'}, 
      {color: 'green'}, 
      {color: 'red'}, 
      {color: 'purple'}, 
      {color: 'green'}, 
      {color: 'red'}, 
      {color: 'green'}
    ],
    [
      {color: 'blue'}, 
      {color: 'red'}, 
      {color: 'purple'}, 
      {color: 'green'}, 
      {color: 'purple'}, 
      {color: 'green'}, 
      {color: 'red'}, 
      {color: 'purple'}, 
      {color: 'green'}, 
      {color: 'red'}, 
      {color: 'green'}
    ],
    [
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ],
    [
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ],
    [
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ],[
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ],
    [
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ],
    [
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ],
    [
      {color: null}, 
      {color: null}, 
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null},  
      {color: null}, 
      {color: null}, 
      {color: null}
    ]
  ],
  bubbleToShoot: {color: null}
}